<a href="https://colab.research.google.com/github/sarishma123/PYTHON_4TH-SEM/blob/main/Sarishma_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,45])
print(arr)

[ 1  2  3 45]


In [ ]:
np.array([[1,2,3,4,5],[10,20,30,40,50]])


array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
a=np.zeros((3,4))
print(a)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
a.shape

(3, 4)

In [ ]:
a.ndim

2

In [ ]:
a.size

12

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [ ]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

<h1> intro to numpy


In [ ]:
print (np.linspace(0,5/3,6))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [ ]:
print(np.arange(0,5/3,0.333333))

[0.    0.333 0.666 0.999 1.332 1.665]


In [ ]:
print(np.arange(0,5/3,0.3333334))

[0.        0.3333334 0.6666668 1.0000002 1.3333336]


In [ ]:
np.random.rand(3,4)

array([[0.3998585 , 0.02033642, 0.77252425, 0.76172637],
       [0.31759664, 0.21823383, 0.13103345, 0.51010503],
       [0.3718657 , 0.98939348, 0.08119703, 0.49228066]])

In [ ]:
np.random.randn(3,4)

array([[ 0.18083313,  0.95026199,  0.92275198, -1.41325311],
       [ 0.6855028 , -0.00486953, -2.6090121 , -1.65338319],
       [-0.32612471,  0.1772718 , -0.10110221,  0.1293018 ]])

In [ ]:
d=np.arange(1,5,dtype=np.complex64)
print(d.dtype,d)

complex64 [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [ ]:
e= np.arange(1,5,dtype=np.complex128)
e.itemsize

16

In [ ]:
e= np.arange(1,5,dtype=np.float128)
print(d.dtype,d)

complex64 [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [ ]:
g= np.arange(24)
print(g)
print("rank:",g.ndim)
print("shape:",g.shape)
print("size:",g.size)
print("data type:",g.dtype)
print("item size:",g.itemsize)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
rank: 1
shape: (24,)
size: 24
data type: int64
item size: 8


In [ ]:
g= np.arange(4)
print(g)
print("shape",g.shape)

[0 1 2 3]
shape (4,)


In [ ]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [ ]:

a = np.full((2, 2), 2)
print("Original array:")
print(a)

a = a.reshape(1, 4)
print("\nReshaped array:")
print(a)

print("\nDimensions:", a.ndim)



Original array:
[[2 2]
 [2 2]]

Reshaped array:
[[2 2 2 2]]

Dimensions: 2


In [ ]:
g2 = np.full((3,4), 2)
g2[1,2]=999
print(g2)

[[  2   2   2   2]
 [  2   2 999   2]
 [  2   2   2   2]]


In [ ]:
g2.ravel()

array([  2,   2,   2,   2,   2,   2, 999,   2,   2,   2,   2,   2])

In [ ]:
a=g.reshape(1,4)
print("\n reshape")
print(a)



 reshape
[[0 1 2 3]]


In [ ]:
b=np.full((3,4),2)
print(b)
b=b.flatten()

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [ ]:
b=b.reshape(-1)
print(b)

[2 2 2 2 2 2 2 2 2 2 2 2]


In [ ]:

a = np.array([34, 56, 43, 23, 43, 5, 6])
b = np.array([3, 44, 54, 6, 7, 6, 4])

print("Array a:", a)
print("Array b:", b)
print("---")

print("Add: ", np.add(a, b))
print("Sub: ", np.subtract(a, b))
print("Mul: ", np.multiply(a, b))
print("Div: ", np.divide(a, b))

Array a: [34 56 43 23 43  5  6]
Array b: [ 3 44 54  6  7  6  4]
---
Add:  [ 37 100  97  29  50  11  10]
Sub:  [ 31  12 -11  17  36  -1   2]
Mul:  [ 102 2464 2322  138  301   30   24]
Div:  [11.33333333  1.27272727  0.7962963   3.83333333  6.14285714  0.83333333
  1.5       ]
