<a href="https://colab.research.google.com/github/sarishma123/PYTHON_4TH-SEM/blob/main/sarishmaday2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.importing the numpy


In [ ]:
import numpy as np

BROADCASTING

2.knowing the dimension of array
and second rule of broadcasting


In [ ]:
h=np.arange(5).reshape(1,1,5)
h+[10,20,30,40,50]
print("the shape of this is:",h.shape)
print("the dimension is: ", h.ndim)

the shape of this is: (1, 1, 5)
the dimension is:  3


3.third rule as 1 and 2 rule of the size of all array must match


In [ ]:
a=[1,2]
b=[[1,2]]
print("the dimension of a is :", np.array(a).ndim)
print("the dimension of b is :", np.array(b).ndim)
print("the shape of a is :", np.array(a).shape)
print("the shape of b is :", np.array(b).shape)

the dimension of a is : 1
the dimension of b is : 2
the shape of a is : (2,)
the shape of b is : (1, 2)


*.Pratice question after 3rd rules

1.create a array and using broadcasting adding to 10 to every element


In [ ]:
arr=np.array([5,10,15,20,25])
result=arr+10
print("the result is:",result)

the result is: [15 20 25 30 35]


2.create the matrix and using broadcasting,add the row vector  ti every row

In [ ]:
matrix= np.array([[1,2,3],[4,5,6],[7,8,9]])
row_vector=np.array([10,20,30])
result=matrix+row_vector
print("the result is:",result)

the result is: [[11 22 33]
 [14 25 36]
 [17 28 39]]


3.create matrix and using broadcasting add the column verctor


In [ ]:
arr1=np.array([[10,20,30],[40,50,60],[70,80,90]])
col_vector=np.array([[1],[2],[3]])
result=arr1+col_vector
print("the result is:",result)

the result is: [[11 21 31]
 [42 52 62]
 [73 83 93]]


4.create matrix and uisng broadcasting,create a matrix where every elemnt is the sum of one value from A and one from B

In [ ]:
A=np.array([1,2,3])
B=np.array([10,20,30,40])
result=A[:,np.newaxis]+B
print("the result is:",result)


the result is: [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


5.Create the matrix and calculate the average of the student after the bonous added..bonus for each subject is [5,3,2]

In [ ]:
A=np.array([[65,70,75],[80,85,90],[55,60,65],[95,90,85]])
bonus=np.array([5,3,2])
result=A+bonus
print("the result is:",result)


the result is: [[ 70  73  77]
 [ 85  88  92]
 [ 60  63  67]
 [100  93  87]]


UPCASTING


1.knowing the uint dataype and others

In [27]:
k1 = np.arange(0, 5, dtype=np.uint8)
k2 = np.arange(5, 10, dtype=np.int64)

# Print the array values
print("Array:", k2)

# Print the data type
print("Data type:", k2.dtype)

Array: [5 6 7 8 9]
Data type: int64


Mathetical and statical function for differnt variable

In [25]:
m=np.array([[-2.5,3.1,7],[10,11,12]])
for func in(m.min,m.max,m.sum,m.std,m.var,m.mean):
  print(func.__name__,"=",func())

min = -2.5
max = 12.0
sum = 40.6
std = 5.084835843520964
var = 25.855555555555554
mean = 6.766666666666667
